### ISSUE TITLE
Support jest coverage

### ISSUE THREAD

**Issue by jbaxleyiii** [antoinejaussoin/redux-saga-testing#1]
@antoinejaussoin this library is fantastic! Thank you so much!

Have you had success with using `jest --coverage` when overriding `it`? It seems to fail for my project.

**Comment by antoinejaussoin** [comment]
Thanks :) 

I just tried to run the coverage on this repo, and it seems to be working fine. I need to try on a "real" project though, one with real files to test (here all the code under tests are within the test files themselves...). I'm planning to use this to test my retrospective board project (retro-board), will update my findings here and keep this issue open for now.

**Comment by antoinejaussoin** [comment]
Coverage works just fine, I confirmed it with a real world project (for work) and my own retro-board project.
