### ISSUE TITLE
How to inject/mock the store?

### ISSUE THREAD

**Issue by jesperlndk** [antoinejaussoin/redux-saga-testing#3]
Hey @antoinejaussoin ! 
Great work you have done here.

One question: I have rather complex saga that acts accordingly to the state of my store. I get the state by starting off with `yield select()` of course.

How can I inject/mock my store if I was to use your library for testing my saga?

Thanks!

**Comment by DerekOverlock** [comment]
Hey @jesperlndk 

Not a contributor on this project, but have you tried something like:
```
it('should select from store', result => {
      expect(result).toEqual(select(mySelector));

      return mockSelectedValue;
});
```

`select` is just an effect, you should be able to mock it's return value similar to how you would mock `call`.

**Comment by antoinejaussoin** [comment]
@DerekOverlock exactly right, `select` is just another Saga effect so you can indeed test that it was called, and return whatever value you need for your test. No need to mock anything :)

@jesperlndk Sorry for the delay in my reply!!

**Comment by TAGC** [comment]
I was wondering this too. Might be a good idea to add an example (or update the "all in one" one) to demonstrate this.

**Comment by antoinejaussoin** [comment]
@TAGC this is actually an excellent idea, will do!

**Comment by antoinejaussoin** [comment]
@TAGC, I added a few examples using selectors, thanks for the suggestion (Also added you to the readme)

**Comment by TAGC** [comment]
No worries, thanks for adding it. 👍
