### ISSUE TITLE
How can I explicitly detect generator termination? (Feature Request?)

### ISSUE THREAD

**Issue by mpyw** [antoinejaussoin/redux-saga-testing#6]
```js
function* saga() {
  yield
}
it = sagaHelper(saga())
it('should be undefined (active)', result => {
   expect(result).toBeUndefined()
})
it('should be undefined (terminated)', result => {
   expect(result).toBeUndefined()
})
```

`saga().next()` returns

1. `{ value: undefined, done: false }`
2. `{ value: undefined, done: true }`

How can I tell them?

**Comment by antoinejaussoin** [comment]
Good question, is there any actual use-case to do `yield undefined`?

**Comment by mpyw** [comment]
Actually there are no use-cases for now. However we may miss some bugs in sagas. I'd like to propose the righter way only if it is possible.

**Comment by antoinejaussoin** [comment]
I honestly don't think this should be a problem, it's such an edge case that making redux-saga-testing more complicated because of this doesn't make sense. Unless you have an elegant way of solving this, I'll close the issue :)

**Comment by mpyw** [comment]
Absolutely. I don't want to implement it with a dirty way. Currently I have no good plan so this issue should be closed. Reopen this if we find the elegant way in the future.

**Comment by mpyw** [comment]
Absolutely. I don't want to implement it with a dirty way. Currently I have no good plan so this issue should be closed. Reopen this if we find the elegant way in the future.

**Comment by mpyw** [comment]
The best way is receiving not `result.value` but `result` itself.

```js
it('should be terminated', ({ value, done }) => {
    expect(done).toBeTruthy();
});
```

However, it breaks backward compatibility.
